# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('instagrabber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=100, unique=True)),
                ('instagram_url', models.CharField(max_length=500)),
                ('caption', models.TextField(default='')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('datetime', models.DateTimeField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagrabber.InstaUser')),
            ],
        ),
    ]
