# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagrabber', '0002_instapicture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instapicture',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AddField(
            model_name='instapicture',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
