# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagrabber', '0003_auto_20190430_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='johndoe', max_length=100)),
                ('password', models.CharField(default='123456789', max_length=50)),
                ('search_term', models.CharField(default='instagram', help_text='Termes s\xe9par\xe9s par une virgule, pas de # ni de @.', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
