# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagrabber', '0004_instaconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instaconfig',
            old_name='search_term',
            new_name='search_terms',
        ),
    ]
