# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagrabber', '0006_instaconfig_notif_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaconfig',
            name='backlist',
            field=models.CharField(blank=True, help_text='Usernames s\xe9par\xe9s par une virgule, sans le @.', max_length=500, null=True),
        ),
    ]
