# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagrabber', '0008_auto_20190722_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaconfig',
            name='search_accounts',
            field=models.CharField(default='instagram', help_text='Comptes s\xe9par\xe9s par une virgule sans le @.', max_length=500),
        ),
        migrations.AddField(
            model_name='instaconfig',
            name='search_hashtags',
            field=models.CharField(default='instagram', help_text='Hashtags s\xe9par\xe9s par une virgule sans le #.', max_length=500),
        ),
        migrations.AlterField(
            model_name='instaconfig',
            name='backlist',
            field=models.CharField(blank=True, help_text='Comptes s\xe9par\xe9s par une virgule, sans le @.', max_length=500, null=True),
        ),
    ]
