# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 10:26
from __future__ import unicode_literals

from django.db import migrations

def copy_search_terms(apps, schema_editor):
    InstaConfig = apps.get_model('instagrabber', 'InstaConfig')
    for conf in InstaConfig.objects.all():
        conf.search_accounts = conf.search_terms
        conf.search_hashtags = conf.search_terms
        conf.save()

class Migration(migrations.Migration):

    dependencies = [
        ('instagrabber', '0009_auto_20190722_1224'),
    ]

    operations = [
        migrations.RunPython(copy_search_terms),
    ]
